### ISSUE TITLE
Project Outline - Overview - take 2

### ISSUE THREAD

**Issue by JenniferLMiller** [Mhart12/liftoff-assignments#3]
For your project overview, don't talk about yourself, talk about the purpose of the app.  The customer is the nursery manager, so talk about how it's going to help accomplish their goals.  Also, I don't think mentioning that you are extending a previous project will help your case towards getting an apprenticeship, unless you can clearly differentiate what the current version does vs what the new and improved version will do.

Also instead of saying I have too many ideas to build right now, make a future enhancement section and list some of these ideas.  In fact, as you come up with more, go ahead and add them here even after this assignment is done, to have a list in one place where you can't lose it :)

**Comment by Mhart12** [comment]
Sorry this has taken me some time to get back to, but I have updated the P2 with the newer outline. I'll continue adding onto the outline as I go, like you suggested to improve future versions :)
